name: Response Time CI
on:
  repository_dispatch:
    types: [response_time]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Check status
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@master
        with:
          command: "response-time"
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
