name: Setup CI
on:
  push:
    branches:
      - master
      - main
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
jobs:
  release:
    name: Setup Upptime
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        with:
          command: "setup"
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
