name: Static Site CI
on:
  repository_dispatch:
    types: [static_site]
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
jobs:
  release:
    name: Build status website
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/status-page@master
        with:
          command: "site"
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
