name: Summary CI
on:
  repository_dispatch:
    types: [summary]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
  pull-requests: write
jobs:
  release:
    name: Generate README
    runs-on: ubuntu-latest
    steps:
      - uses: upptime/uptime-monitor@master
        with:
          command: "readme"
        env:
          GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
